name: flutter_gemini_ai_chatbot_using_aiassistview
description: "A Flutter project which showcases Gemini-like chatbot using SfAIAssistView."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core: ^28.1.38
  syncfusion_flutter_chat: ^28.1.38-beta
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ai_assist_view.png
